/*
 * This file is generated by jOOQ.
*/
package org.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.MapGroupRole;


/**
 * 群組角色對應
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapGroupRoleRecord extends UpdatableRecordImpl<MapGroupRoleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 546162054;

    /**
     * Setter for <code>oauth.map_group_role.group_id</code>. 群組ID
     */
    public void setGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth.map_group_role.group_id</code>. 群組ID
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oauth.map_group_role.role_id</code>. 角色ID
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth.map_group_role.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MapGroupRole.MAP_GROUP_ROLE.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MapGroupRole.MAP_GROUP_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapGroupRoleRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapGroupRoleRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapGroupRoleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapGroupRoleRecord
     */
    public MapGroupRoleRecord() {
        super(MapGroupRole.MAP_GROUP_ROLE);
    }

    /**
     * Create a detached, initialised MapGroupRoleRecord
     */
    public MapGroupRoleRecord(Integer groupId, Integer roleId) {
        super(MapGroupRole.MAP_GROUP_ROLE);

        set(0, groupId);
        set(1, roleId);
    }
}
