/*
 * This file is generated by jOOQ.
*/
package org.jooq;


import javax.annotation.Generated;

import org.jooq.impl.Internal;
import org.jooq.tables.Group;
import org.jooq.tables.MapGroupRole;
import org.jooq.tables.MapUserGroup;
import org.jooq.tables.Role;
import org.jooq.tables.User;


/**
 * A class modelling indexes of tables of the <code>oauth</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GROUP_IDX_GROUP = Indexes0.GROUP_IDX_GROUP;
    public static final Index GROUP_PRIMARY = Indexes0.GROUP_PRIMARY;
    public static final Index MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE = Indexes0.MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE;
    public static final Index MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE_0 = Indexes0.MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE_0;
    public static final Index MAP_GROUP_ROLE_PRIMARY = Indexes0.MAP_GROUP_ROLE_PRIMARY;
    public static final Index MAP_USER_GROUP_IDX_MAP_USER_GROUP = Indexes0.MAP_USER_GROUP_IDX_MAP_USER_GROUP;
    public static final Index MAP_USER_GROUP_IDX_MAP_USER_GROUP_0 = Indexes0.MAP_USER_GROUP_IDX_MAP_USER_GROUP_0;
    public static final Index MAP_USER_GROUP_PRIMARY = Indexes0.MAP_USER_GROUP_PRIMARY;
    public static final Index ROLE_IDX_ROLE = Indexes0.ROLE_IDX_ROLE;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index USER_IDX_USER = Indexes0.USER_IDX_USER;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GROUP_IDX_GROUP = Internal.createIndex("idx_group", Group.GROUP, new OrderField[] { Group.GROUP.NAME }, true);
        public static Index GROUP_PRIMARY = Internal.createIndex("PRIMARY", Group.GROUP, new OrderField[] { Group.GROUP.ID }, true);
        public static Index MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE = Internal.createIndex("idx_map_group_role", MapGroupRole.MAP_GROUP_ROLE, new OrderField[] { MapGroupRole.MAP_GROUP_ROLE.GROUP_ID }, false);
        public static Index MAP_GROUP_ROLE_IDX_MAP_GROUP_ROLE_0 = Internal.createIndex("idx_map_group_role_0", MapGroupRole.MAP_GROUP_ROLE, new OrderField[] { MapGroupRole.MAP_GROUP_ROLE.ROLE_ID }, false);
        public static Index MAP_GROUP_ROLE_PRIMARY = Internal.createIndex("PRIMARY", MapGroupRole.MAP_GROUP_ROLE, new OrderField[] { MapGroupRole.MAP_GROUP_ROLE.GROUP_ID, MapGroupRole.MAP_GROUP_ROLE.ROLE_ID }, true);
        public static Index MAP_USER_GROUP_IDX_MAP_USER_GROUP = Internal.createIndex("idx_map_user_group", MapUserGroup.MAP_USER_GROUP, new OrderField[] { MapUserGroup.MAP_USER_GROUP.USER_ID }, false);
        public static Index MAP_USER_GROUP_IDX_MAP_USER_GROUP_0 = Internal.createIndex("idx_map_user_group_0", MapUserGroup.MAP_USER_GROUP, new OrderField[] { MapUserGroup.MAP_USER_GROUP.GROUP_ID }, false);
        public static Index MAP_USER_GROUP_PRIMARY = Internal.createIndex("PRIMARY", MapUserGroup.MAP_USER_GROUP, new OrderField[] { MapUserGroup.MAP_USER_GROUP.USER_ID, MapUserGroup.MAP_USER_GROUP.GROUP_ID }, true);
        public static Index ROLE_IDX_ROLE = Internal.createIndex("idx_role", Role.ROLE, new OrderField[] { Role.ROLE.NAME }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index USER_IDX_USER = Internal.createIndex("idx_user", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
