/*
 * This file is generated by jOOQ.
*/
package org.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.tables.MapGroupRole;
import org.jooq.tables.records.MapGroupRoleRecord;


/**
 * 群組角色對應
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapGroupRoleDao extends DAOImpl<MapGroupRoleRecord, org.jooq.tables.pojos.MapGroupRole, Record2<Integer, Integer>> {

    /**
     * Create a new MapGroupRoleDao without any configuration
     */
    public MapGroupRoleDao() {
        super(MapGroupRole.MAP_GROUP_ROLE, org.jooq.tables.pojos.MapGroupRole.class);
    }

    /**
     * Create a new MapGroupRoleDao with an attached configuration
     */
    public MapGroupRoleDao(Configuration configuration) {
        super(MapGroupRole.MAP_GROUP_ROLE, org.jooq.tables.pojos.MapGroupRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(org.jooq.tables.pojos.MapGroupRole object) {
        return compositeKeyRecord(object.getGroupId(), object.getRoleId());
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<org.jooq.tables.pojos.MapGroupRole> fetchByGroupId(Integer... values) {
        return fetch(MapGroupRole.MAP_GROUP_ROLE.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<org.jooq.tables.pojos.MapGroupRole> fetchByRoleId(Integer... values) {
        return fetch(MapGroupRole.MAP_GROUP_ROLE.ROLE_ID, values);
    }
}
