/*
 * This file is generated by jOOQ.
*/
package org.jooq;


import javax.annotation.Generated;

import org.jooq.tables.Group;
import org.jooq.tables.MapGroupRole;
import org.jooq.tables.MapUserGroup;
import org.jooq.tables.Role;
import org.jooq.tables.User;


/**
 * Convenience access to all tables in oauth
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 群組
     */
    public static final Group GROUP = org.jooq.tables.Group.GROUP;

    /**
     * 群組角色對應
     */
    public static final MapGroupRole MAP_GROUP_ROLE = org.jooq.tables.MapGroupRole.MAP_GROUP_ROLE;

    /**
     * 使用者群組對應
     */
    public static final MapUserGroup MAP_USER_GROUP = org.jooq.tables.MapUserGroup.MAP_USER_GROUP;

    /**
     * 角色
     */
    public static final Role ROLE = org.jooq.tables.Role.ROLE;

    /**
     * 使用者基本資訊
     */
    public static final User USER = org.jooq.tables.User.USER;
}
