/*
 * This file is generated by jOOQ.
*/
package org.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 使用者基本資訊
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1950163424;

    private Integer   id;
    private String    username;
    private String    password;
    private Byte      locked;
    private Byte      enable;
    private Timestamp expiredDate;
    private Timestamp pwdExpiredDate;
    private String    name;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.locked = value.locked;
        this.enable = value.enable;
        this.expiredDate = value.expiredDate;
        this.pwdExpiredDate = value.pwdExpiredDate;
        this.name = value.name;
    }

    public User(
        Integer   id,
        String    username,
        String    password,
        Byte      locked,
        Byte      enable,
        Timestamp expiredDate,
        Timestamp pwdExpiredDate,
        String    name
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.locked = locked;
        this.enable = enable;
        this.expiredDate = expiredDate;
        this.pwdExpiredDate = pwdExpiredDate;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Byte getLocked() {
        return this.locked;
    }

    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    public Byte getEnable() {
        return this.enable;
    }

    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    public Timestamp getExpiredDate() {
        return this.expiredDate;
    }

    public void setExpiredDate(Timestamp expiredDate) {
        this.expiredDate = expiredDate;
    }

    public Timestamp getPwdExpiredDate() {
        return this.pwdExpiredDate;
    }

    public void setPwdExpiredDate(Timestamp pwdExpiredDate) {
        this.pwdExpiredDate = pwdExpiredDate;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(locked);
        sb.append(", ").append(enable);
        sb.append(", ").append(expiredDate);
        sb.append(", ").append(pwdExpiredDate);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
